CREATE TABLE ST.GUEG_SALARY_HIST (
    PERSON VARCHAR(255),
    CLASS VARCHAR(255),
    SALARY DECIMAL(10, 2),
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE
);

INSERT INTO ST.GUEG_SALARY_HIST (PERSON, CLASS, SALARY, EFFECTIVE_FROM, EFFECTIVE_TO)
SELECT 
    PERSON,
    CLASS,
    SALARY,
    EFFECTIVE_FROM,
    LEAD(EFFECTIVE_FROM, 1, '9999-12-31') OVER (PARTITION BY PERSON ORDER BY EFFECTIVE_FROM) - INTERVAL '1 DAY' AS EFFECTIVE_TO
FROM (
    SELECT 
        PERSON,
        CLASS,
        SALARY,
        EFFECTIVE_FROM,
        ROW_NUMBER() OVER (PARTITION BY PERSON ORDER BY EFFECTIVE_FROM) AS rn
    FROM DE.HISTGROUP
) AS subquery
WHERE rn = 1 OR SALARY != LAG(SALARY) OVER (PARTITION BY PERSON ORDER BY EFFECTIVE_FROM);
