CREATE TABLE ST.GUEG_SALARY_LOG (
    PAYMENT_DT DATE,
    PERSON VARCHAR(255),
    PAYMENT DECIMAL(10, 2),
    MONTH_PAID DECIMAL(10, 2),
    MONTH_REST DECIMAL(10, 2)
);

INSERT INTO ST.GUEG_SALARY_LOG (PAYMENT_DT, PERSON, PAYMENT, MONTH_PAID, MONTH_REST)
SELECT 
    sp.PAYMENT_DT,
    sp.PERSON,
    sp.PAYMENT,
    SUM(sp.PAYMENT) OVER (PARTITION BY sp.PERSON, DATE_TRUNC('month', sp.PAYMENT_DT)) AS MONTH_PAID,
    sh.SALARY - SUM(sp.PAYMENT) OVER (PARTITION BY sp.PERSON, DATE_TRUNC('month', sp.PAYMENT_DT)) AS MONTH_REST
FROM DE.SALARY_PAYMENTS sp
JOIN ST.GUEG_SALARY_HIST sh ON sp.PERSON = sh.PERSON 
                             AND sp.PAYMENT_DT BETWEEN sh.EFFECTIVE_FROM AND sh.EFFECTIVE_TO;
